- name: 创建data目录
  shell: sudo mkdir -p /server/data/docker/gitlab/data
- name: 创建日志目
  shell: sudo mkdir -p /server/data/docker/gitlab/logs
- name: 创建配置目录
  shell: sudo mkdir -p /server/data/docker/gitlab/config
- name: 复制配置文件到指定目录
  template: src=roles/gitlab/templates/gitlab.rb dest=/server/data/docker/gitlab/config/gitlab.rb
- name: 拉取镜像
  shell: docker pull {{gitlab_image_name}}
- name: 创建容器
  shell: >
      docker run --detach \
      --publish {{gitlab_port_443}}:443 --publish {{gitlab_port_80}}:80 --publish {{gitlab_port_22}}:22 \
      --name {{gitlab_process_name}} \
      --restart always \
      --volume /server/data/docker/gitlab/config:/etc/gitlab \
      --volume /server/data/docker/gitlab/logs:/var/log/gitlab \
      --volume /server/data/docker/gitlab/data:/var/opt/gitlab \
      {{gitlab_image_name}}
