- name: 安装mysql的docker镜像
  shell: docker pull {{mysql_image_name}}
- name: 创建挂载mysql数据文件的目录
  shell: mkdir -p /server/data/docker/mysql/master/datadir
- name: 停止原来的docker容器
  shell: docker stop {{mysql_process_name}}
- name: 删除原来的容器
  shell: docker rm {{mysql_process_name}}
- name: 生成mysqld.cnf
  template: src=roles/mysql/templates/mysqld.cnf.j2 dest=/server/data/docker/mysql/master/mysqld.cnf
- name: 启动mysql容器
  shell: >
      docker run --name {{mysql_process_name}} -p {{mysql_port}}:3306 --restart=always --privileged=true \
        -v /server/data/docker/mysql/master/datadir:/var/lib/mysql \
        -v /server/data/docker/mysql/master/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf \
        -e MYSQL_ROOT_PASSWORD={{mysql_root_password}} \
        -d {{mysql_image_name}} \
        --character-set-server=utf8mb4 \
        --collation-server=utf8mb4_unicode_ci

